### DISCUSSION TITLE
有无限制玩家 创建商店方块(箱子)数量

### DISCUSSION THREAD

**Discussion by 8MiYile** [QuickShop-Community/QuickShop-Hikari#1719] [Q&A] [answered]

**Comment by YuanYuanOwO** [comment, marked as answer]
第一个问题见此
https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/modules/shops/ranks
关于第二个问题，请开一个issue，目前做不到

**Reply by 8MiYile** [reply]
哦哦 原来叫rank啊 我一直搜索maximum搜不到 谢谢

**Reply by 8MiYile** [reply]
https://quickshop-community.github.io/QuickShop-Hikari-Documents/zh-CN/docs/modules/shops/ranks#permission-node-generation

Does it support this
e.g. quickshop.create-level.vip1 etc.?
```yaml
limits:
  ranks:
    quickshop:
      create-level:
        vip1: 0
```
